package maniac.lee.shardy.core;

import maniac.lee.shardy.core.wrap.AbstractShardyStatement;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * Created by peng on 16/6/1.
 */
public class ShardyStatement extends AbstractShardyStatement {

    @Override
    public boolean doExecute(String sql, int autoGeneratedKeys, int[] columnIndexes, String[] columnNames) {
        return false;
    }

    @Override
    public int doExecuteUpdate(String sql, int autoGeneratedKeys, int[] columnIndexes, String[] columnNames) {
        return 0;
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        return super.executeQuery(sql);
    }
}
